# Generated by Django 4.2.5 on 2024-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_interview_pruned_p_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='p_notes',
            field=models.TextField(default='{ }'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='pruned_p_notes',
            field=models.TextField(default='{ }'),
        ),
    ]
