# Generated by Django 4.2.5 on 2024-02-01 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_perfmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='completed_modules_det',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TimeoutTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
