# Generated by Django 4.2.5 on 2024-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_participant_completed_modules_det_timeouttimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeouttimer',
            name='cause',
            field=models.TextField(blank=True, default=''),
        ),
    ]
