# Generated by Django 4.2.5 on 2024-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_timeouttimer_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='q_max_sec',
            field=models.FloatField(default=1),
        ),
    ]
