# Generated by Django 4.2.5 on 2024-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_interviewquestion_q_max_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='q_condition',
            field=models.TextField(default=''),
        ),
    ]
