# Generated by Django 4.2.5 on 2024-03-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_interviewquestion_q_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralStudyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_cond', models.CharField(default='0101110010110010101001010010100001001011', max_length=127)),
                ('study_rand_o_1', models.TextField(blank=True, default="{ 'study_num': { 'study_link': 'link', 'study_val_code': 'code' } }")),
                ('study_completed_1', models.TextField(blank=True, default='')),
                ('study_rand_o_2', models.TextField(blank=True, default="{ 'study_num': { 'study_link': 'link', 'study_val_code': 'code' } }")),
                ('study_completed_2', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='behavioral_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='behavioral_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.behavioralstudymodule'),
        ),
    ]
