# Generated by Django 4.2.5 on 2024-03-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_behavioralstudymodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavioralstudymodule',
            name='study_completed_1',
        ),
        migrations.RemoveField(
            model_name='behavioralstudymodule',
            name='study_completed_2',
        ),
    ]
