# Generated by Django 4.2.5 on 2024-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_behavioralstudymodule_study_completed_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='camerer_activated',
            field=models.TextField(blank=True, default=''),
        ),
    ]
