# Generated by Django 4.2.5 on 2024-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_participant_camerer_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='zipped_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='zipped_main',
            field=models.BooleanField(default=False),
        ),
    ]
