# Generated by Django 4.2.5 on 2024-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_interviewquestion_zipped_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='zipped_audio',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='zipped_main',
        ),
        migrations.AddField(
            model_name='interview',
            name='zipped_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='zipped_main',
            field=models.BooleanField(default=False),
        ),
    ]
