# Generated by Django 4.2.5 on 2025-03-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_interviewrecommendation_interviewclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRecommendationSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_score', models.IntegerField(help_text='Score from 0-100 indicating level of support')),
                ('confidence_score', models.IntegerField(help_text='Score from 0-100 indicating confidence in prediction')),
                ('explanation', models.TextField(help_text="Explanation for why the participant would/wouldn't support")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.interview')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.interviewrecommendation')),
            ],
            options={
                'unique_together': {('recommendation', 'interview')},
            },
        ),
    ]
