# Generated by Django 4.2.5 on 2025-03-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_add_audio_id_to_interviewclip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewclip',
            name='audio_id',
        ),
    ]
