# Generated by Django 4.2.5 on 2025-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_interviewclip_audio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewclip',
            name='audio_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
