# Generated by Django 4.2.5 on 2025-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_interviewclip_audio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrecommendationsupport',
            name='is_endorsed',
            field=models.BooleanField(default=False, help_text='Whether the participant has endorsed this explanation'),
        ),
        migrations.AddField(
            model_name='participantrecommendationsupport',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='When the explanation was last modified'),
        ),
        migrations.AddField(
            model_name='participantrecommendationsupport',
            name='user_modified_explanation',
            field=models.TextField(blank=True, help_text="User's modified explanation if they chose to edit it", null=True),
        ),
    ]
