# Generated by Django 4.2.5 on 2025-04-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_participantrecommendationsupport_is_endorsed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_text', models.TextField()),
                ('audio_id', models.IntegerField(blank=True, null=True)),
                ('is_interviewer', models.BooleanField()),
                ('sequence_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='pages.interviewquestion')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
