# Generated by Django 4.2.5 on 2025-05-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_interviewutterance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_text', models.TextField()),
                ('utterances', models.ManyToManyField(related_name='recommendations', to='pages.interviewutterance')),
            ],
        ),
    ]
