# Generated by Django 4.2.5 on 2025-05-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewutterance',
            name='is_redacted',
            field=models.BooleanField(default=False),
        ),
    ]
