# Generated by Django 4.2.5 on 2025-05-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_interviewutterance_is_redacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='prolific_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
