# Generated by Django 4.2.5 on 2025-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_participant_prolific_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='prolific_id',
            field=models.CharField(null = True, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
