# Generated by Django 4.2.5 on 2025-06-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_participant_prolific_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationParticipantSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text="AI-generated summary of how the participant's experiences relate to this recommendation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
            ],
            options={
                'verbose_name_plural': 'Recommendation participant summaries',
                'unique_together': {('recommendation', 'participant')},
            },
        ),
    ]
