# Generated by Django 4.2.5 on 2025-06-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_participant_prolific_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='best_utterance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.interviewutterance'),
        ),
    ]
