# Generated by Django 4.2.5 on 2025-06-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_recommendationparticipantsummary_best_utterance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='pages.narrative')),
                ('utterance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.interviewutterance')),
            ],
        ),
    ]
