# Generated by Django 4.2.5 on 2025-06-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_narrative_narrativepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativepart',
            name='ai_explanation_text',
            field=models.TextField(blank=True, help_text='Text of the AI explanation, if this part is an explanation', null=True),
        ),
        migrations.AlterField(
            model_name='narrativepart',
            name='utterance',
            field=models.ForeignKey(blank=True, help_text='Reference to an utterance, if this part is a quote', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.interviewutterance'),
        ),
    ]
