# Generated by Django 4.2.5 on 2025-06-13 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_narrativepart_ai_explanation_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_level', models.IntegerField(help_text='Level of agreement with the recommendation (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('importance_level', models.IntegerField(help_text='Level of importance for implementing the recommendation (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('confidence_level', models.IntegerField(help_text='Level of confidence in the stance (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('explanation', models.TextField(help_text="Explanation for the vote, including evidence from own and others' experiences")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
            ],
            options={
                'verbose_name': 'Recommendation Vote',
                'verbose_name_plural': 'Recommendation Votes',
                'unique_together': {('recommendation', 'participant')},
            },
        ),
    ]
