# Generated by Django 4.2.5 on 2025-06-19 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_narrative_unique_together_recommendationvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='confidence_score',
            field=models.IntegerField(blank=True, help_text='Confidence in the prediction (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='predicted_agreement',
            field=models.IntegerField(blank=True, help_text='Predicted agreement level (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Reasoning for the predicted vote', null=True),
        )
    ]
