# Generated by Django 4.2.5 on 2025-06-26 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_narrative_unique_together_recommendationvote'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='participant',
        #     name='age',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='participant',
        #     name='occupation',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='narrative',
        #     unique_together={('recommendation', 'participant')},
        # ),
        # migrations.CreateModel(
        #     name='ParticipantReflection',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('connection_score', models.IntegerField(blank=True, null=True)),
        #         ('connection_text', models.TextField(blank=True, null=True)),
        #         ('vote_prediction', models.IntegerField(blank=True, null=True)),
        #         ('vote_explanation', models.TextField(blank=True, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
        #         ('target_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflected_on', to=settings.AUTH_USER_MODEL)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='ConnectionRequest',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
        #         ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
        #         ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
        #         ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
