# Generated by Django 4.2.5 on 2025-06-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_participant_age_participant_occupation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='narrative',
            unique_together={('recommendation', 'participant')},
        ),
    ]
