# Generated by Django 4.2.5 on 2025-06-19 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_recommendationparticipantsummary_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='relevance_score',
            field=models.IntegerField(blank=True, help_text='Relevance score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        )
    ]
