# Generated by Django 4.2.5 on 2025-06-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_recommendationparticipantsummary_relevance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='utterances',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='pages.interviewutterance'),
        ),
        migrations.CreateModel(
            name='ParticipantRecommendationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('current_predictions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_versions', to='pages.recommendation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant Recommendation Version',
                'verbose_name_plural': 'Participant Recommendation Versions',
                'unique_together': {('original_recommendation', 'participant')},
            },
        ),
    ]
