# Generated by Django 4.2.5 on 2025-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_narrative_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
