# Generated by Django 4.2.5 on 2025-06-23 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_recommendation_utterances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_texts', models.JSONField(default=list, help_text='List of edited recommendation texts by the participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editable_recommendations', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editable_recommendations', to='pages.recommendation')),
            ],
        ),
        migrations.DeleteModel(
            name='ParticipantRecommendationVersion',
        ),
    ]
