# Generated by Django 4.2.5 on 2025-06-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_participantreflection_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativepart',
            name='utterance_text_with_bold',
            field=models.TextField(blank=True, help_text='AI-generated utterance text with bold tags for highlighting', null=True),
        ),
    ]
