# Generated by Django 4.2.5 on 2025-07-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_narrativepart_utterance_text_with_bold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantNarrativePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_text_with_bold', models.TextField(blank=True, help_text='AI-generated utterance text with bold tags for highlighting', null=True)),
                ('ai_explanation_text', models.TextField(blank=True, help_text='Text of the AI explanation, if this part is an explanation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.participantnarrative')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.interviewutterance')),
            ],
        )
    ]
