# Generated by Django 4.2.5 on 2025-07-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_editablerecommendation_and_more'),
        ('pages', '0037_participantnarrative_participantnarrativepart_and_more'),
    ]

    operations = [
    ]
