# Generated by Django 4.2.5 on 2025-07-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_merge_20250703_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='global_summary',
            field=models.TextField(blank=True, help_text="AI-generated summary of the participant's experiences related to the recommendation", null=True),
        ),
        migrations.AddField(
            model_name='participantnarrative',
            name='global_summary',
            field=models.TextField(blank=True, help_text="AI-generated summary of the participant's experiences", null=True),
        )
    ]
