# Generated by Django 4.2.5 on 2025-07-17 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_narrative_global_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_score', models.IntegerField(blank=True, null=True)),
                ('connection_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedVoteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_vote_score', models.IntegerField(blank=True, null=True)),
                ('predicted_vote_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vote_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='predictedvotereport',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='predictedvotereport',
            name='target_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_vote_reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectionreport',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='connectionreport',
            name='target_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_reports_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
