# Generated by Django 4.2.5 on 2025-07-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_connectionreport_predictedvotereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('too_high', 'My support is lower than predicted'), ('too_low', 'My support is higher than predicted'), ('neutral', "I'm neutral/unsure about this recommendation"), ('other', 'Other reason')], help_text='Type of feedback provided', max_length=20)),
                ('feedback_text', models.TextField(blank=True, help_text='Additional comments from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Feedback',
                'verbose_name_plural': 'Prediction Feedback',
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='participant_who_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantnarrativepart',
            name='participant_narrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='pages.participantnarrative'),
        ),
        migrations.DeleteModel(
            name='EditableRecommendation',
        ),
        migrations.AddField(
            model_name='predictionfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='predictionfeedback',
            unique_together={('participant', 'recommendation')},
        ),
    ]
