# Generated by Django 4.2.5 on 2025-07-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_create_prediction_feedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
