# Generated by Django 4.2.5 on 2025-07-21 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_participant_display_name_recommendation_base_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_participants', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_selections_as_current', to='pages.participant')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation')),
            ],
            options={
                'unique_together': {('current_user', 'recommendation')},
            },
        ),
        migrations.AddIndex(
            model_name='participantsimilarity',
            index=models.Index(fields=['current_user', 'recommendation'], name='pages_participant_similarity_current_user_recommendation_idx'),
        ),
    ]
