# Generated by Django 4.2.5 on 2025-07-26 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_add_participant_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_outcome', models.CharField(choices=[('PASS', 'Pass'), ('NOT_PASS', 'Not Pass')], help_text='The decision outcome based on majority vote', max_length=10)),
                ('trust_decision', models.IntegerField(help_text="I trust that this decision accurately reflects participants' views (1-7)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('input_valuable', models.IntegerField(help_text='I felt that my input was valuable (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('willing_abide', models.IntegerField(help_text='I would be willing to abide by this decision (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('understand_others', models.IntegerField(help_text='I understand why others voted the way they did on the decision (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('share_values', models.IntegerField(help_text='I probably share common values with people that voted on this decision (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('confident_vote', models.IntegerField(help_text='I am confident in my original vote on this proposal (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Decision Feedback',
                'verbose_name_plural': 'Decision Feedback',
            },
        ),
        migrations.AddField(
            model_name='decisionfeedback',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionfeedback',
            unique_together={('recommendation', 'participant')},
        ),
    ]
