# Generated by Django 4.2.5 on 2025-07-26 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_decisionfeedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationvote',
            name='confidence_level',
            field=models.IntegerField(blank=True, help_text='Level of confidence in the stance (1-7)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='recommendationvote',
            name='importance_level',
            field=models.IntegerField(blank=True, help_text='Level of importance for implementing the recommendation (1-7)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
