# Generated by Django 4.2.5 on 2025-07-22 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_rename_pages_participant_similarity_current_user_recommendation_idx_pages_parti_current_058802_idx_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClipListening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_audio_duration', models.FloatField(blank=True, help_text='Total duration of audio clip in seconds', null=True)),
                ('listened_duration', models.FloatField(blank=True, help_text='How much of the audio was actually listened to', null=True)),
                ('completion_percentage', models.FloatField(blank=True, help_text='Percentage of audio completed (0-100)', null=True)),
                ('play_count', models.IntegerField(default=0, help_text='Number of times audio was played')),
                ('pause_count', models.IntegerField(default=0, help_text='Number of times audio was paused')),
                ('seek_count', models.IntegerField(default=0, help_text='Number of times user seeked in audio')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_type', models.CharField(choices=[('featured', 'Featured Avatar'), ('current_user', 'Current User Avatar'), ('other', 'Other Avatar')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('click_x', models.IntegerField(blank=True, null=True)),
                ('click_y', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfileTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationTimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),

        migrations.AddField(
            model_name='votingscreentime',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_screen_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingscreentime',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_screen_times', to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='recommendationtimespent',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationtimespent',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_times', to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='participantprofiletime',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantprofiletime',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_times', to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='participantprofiletime',
            name='viewed_participant',
            field=models.ForeignKey(help_text='The participant whose profile was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatarclick',
            name='clicked_participant',
            field=models.ForeignKey(help_text='The participant whose avatar was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatarclick',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatarclick',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_clicks', to='pages.recommendation'),
        ),
        migrations.AddField(
            model_name='audiocliplistening',
            name='audio_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='pages.interviewclip'),
        ),
        migrations.AddField(
            model_name='audiocliplistening',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_listening_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiocliplistening',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_listening_sessions', to='pages.recommendation'),
        ),
        migrations.AddIndex(
            model_name='votingscreentime',
            index=models.Index(fields=['participant', 'recommendation'], name='pages_votin_partici_f4f0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='votingscreentime',
            index=models.Index(fields=['started_at'], name='pages_votin_started_b21fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationtimespent',
            index=models.Index(fields=['participant', 'recommendation'], name='pages_recom_partici_d0834f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationtimespent',
            index=models.Index(fields=['started_at'], name='pages_recom_started_b204d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationtimespent',
            unique_together={('participant', 'recommendation', 'session_id')},
        ),
        migrations.AddIndex(
            model_name='participantprofiletime',
            index=models.Index(fields=['participant', 'recommendation'], name='pages_parti_partici_937c61_idx'),
        ),
        migrations.AddIndex(
            model_name='participantprofiletime',
            index=models.Index(fields=['viewed_participant'], name='pages_parti_viewed__289779_idx'),
        ),
        migrations.AddIndex(
            model_name='participantprofiletime',
            index=models.Index(fields=['started_at'], name='pages_parti_started_c523f2_idx'),
        ),
        migrations.AddIndex(
            model_name='avatarclick',
            index=models.Index(fields=['participant', 'recommendation'], name='pages_avata_partici_148e17_idx'),
        ),
        migrations.AddIndex(
            model_name='avatarclick',
            index=models.Index(fields=['avatar_type', 'timestamp'], name='pages_avata_avatar__5fddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='avatarclick',
            index=models.Index(fields=['clicked_participant'], name='pages_avata_clicked_f0089f_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocliplistening',
            index=models.Index(fields=['participant', 'recommendation'], name='pages_audio_partici_96814f_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocliplistening',
            index=models.Index(fields=['audio_clip'], name='pages_audio_audio_c_b39640_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocliplistening',
            index=models.Index(fields=['started_at'], name='pages_audio_started_0f6440_idx'),
        ),
    ]