# Generated by Django 4.2.5 on 2025-07-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_add_telemetry_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participantsimilarity',
            new_name='pages_parti_current_058802_idx',
            old_name='pages_participant_similarity_current_user_recommendation_idx',
        ),
        migrations.AddField(
            model_name='audiocliplistening',
            name='audio_id',
            field=models.IntegerField(blank=True, help_text='Audio ID from InterviewUtterance', null=True),
        ),
        migrations.AlterField(
            model_name='audiocliplistening',
            name='audio_clip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='pages.interviewclip'),
        ),
    ]