# Generated by Django 4.2.5 on 2025-07-28 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_add_audio_id_to_audiocliplistening'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='base_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_recommendations', to='pages.recommendation'),
        ),
    ]
