# Generated by Django 4.2.5 on 2025-08-01 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_add_profile_selection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='coherence_score',
            field=models.IntegerField(blank=True, help_text='Coherence score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
