# Generated by Django 4.2.5 on 2025-08-04 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_recommendationparticipantsummary_coherence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_order', models.JSONField(help_text='Randomized order of recommendations 74, 75, 76')),
                ('current_index', models.IntegerField(default=0, help_text='Current position in the recommendation order (0-based index)')),
                ('completed', models.BooleanField(default=False, help_text='Whether the user has completed all recommendations in the order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommendation Order',
                'verbose_name_plural': 'User Recommendation Orders',
                'db_table': 'user_recommendation_order',
            },
        ),
    ]
