# Generated by Django 4.2.5 on 2025-08-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_add_user_recommendation_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecommendationOrder',
        ),
    ]
