# Generated by Django 4.2.5 on 2025-08-06 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_delete_userrecommendationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Weighted quality score combining opinion, relevance, and depth (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
