# Generated by Django 4.2.5 on 2025-08-06 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_add_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationparticipantsummary',
            name='opinion_vs_experience_score',
            field=models.IntegerField(blank=True, help_text='Opinion vs Experience score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
