# Generated by Django 4.2.5 on 2025-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_add_generated_avatar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='ai_predicted_support',
            field=models.FloatField(blank=True, help_text='Average predicted support percentage for AI recommendation (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ai_rec_text',
            field=models.TextField(blank=True, help_text='AI-generated consensus recommendation text', null=True),
        ),
    ]
