# Generated by Django 4.2.5 on 2025-10-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_recommendation_ai_predicted_support_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('segment_audio_file', models.FileField(blank=True, null=True, upload_to='InterviewAudios/')),
                ('segment_text', models.TextField()),
                ('sequence_number', models.IntegerField(default=1)),
                ('word_count', models.IntegerField(blank=True, help_text='Number of words in segment', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='pages.interviewaudio')),
            ],
            options={
                'ordering': ['audio', 'sequence_number'],
                'indexes': [models.Index(fields=['audio', 'sequence_number'], name='pages_inter_audio_i_511d05_idx')],
                'unique_together': {('audio', 'sequence_number')},
            },
        ),
    ]
