# Generated by Django 4.2.5 on 2025-10-25 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_interviewsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.FloatField(default=0.0, help_text='Actual total duration in seconds')),
                ('gpt_estimated_duration', models.FloatField(blank=True, help_text="GPT's estimated duration in seconds", null=True)),
                ('segment_count', models.IntegerField(default=0)),
                ('gpt_reasoning', models.TextField(blank=True, default='')),
                ('reordered', models.BooleanField(default=False)),
                ('recommendation_text', models.TextField(blank=True, default='')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score for the medley (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medleys', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medleys', to='pages.recommendation')),
                ('segments', models.ManyToManyField(blank=True, related_name='medleys', to='pages.interviewsegment')),
                ('utterances', models.ManyToManyField(blank=True, related_name='medleys', to='pages.interviewutterance')),
            ],
            options={
                'verbose_name_plural': 'Medleys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant', 'recommendation'], name='pages_medle_partici_539486_idx'), models.Index(fields=['created_at'], name='pages_medle_created_9f1520_idx')],
            },
        ),
        migrations.CreateModel(
            name='LivePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_agreement', models.IntegerField(help_text='Predicted agreement level (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_score', models.IntegerField(help_text='Confidence in the prediction (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reasoning', models.TextField(help_text='Explanation for the predicted agreement level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_predictions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_predictions', to='pages.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recommendation', 'participant')},
            },
        ),
    ]
