# Generated by Django 4.2.5 on 2025-11-03 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_medley_liveprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMedley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_segments', models.JSONField(blank=True, default=list)),
                ('total_duration', models.FloatField(default=0.0)),
                ('segment_count', models.IntegerField(default=0)),
                ('gpt_reasoning', models.TextField(blank=True, default='')),
                ('participant_cache_key', models.CharField(blank=True, default='', max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='meta_medleys', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_medleys', to='pages.recommendation')),
                ('source_medleys', models.ManyToManyField(related_name='meta_medleys', to='pages.medley')),
            ],
            options={
                'verbose_name_plural': 'Meta Medleys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recommendation', 'participant_cache_key'], name='pages_metam_recomme_d5563a_idx'), models.Index(fields=['created_at'], name='pages_metam_created_eeb26a_idx')],
            },
        ),
    ]
