# Generated by Django 4.2.5 on 2025-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_metamedley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamedley',
            name='participant_cache_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
