# Generated by Django 4.2.5 on 2025-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_recommendation_created_at_recommendation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarclick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='avatarclick',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
