# Generated by Django 4.2.5 on 2025-11-11 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_avatarclick_created_at_avatarclick_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMedleyClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_medley_type', models.CharField(choices=[('bottom', 'Bottom (Against)'), ('middle', 'Middle (On the fence)'), ('top', 'Top (For)')], max_length=20)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for tracking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_medley_clicks', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_medley_clicks', to='pages.recommendation')),
            ],
        ),
    ]
