# Generated by Django 4.2.5 on 2025-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_metamedleyclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='prolific_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
