# Generated by Django 4.2.5 on 2025-12-08 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_metamedleyclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pages.chatconversation')),
            ],
            options={
                'ordering': ['conversation', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ChatMedley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_segments', models.JSONField()),
                ('total_duration', models.FloatField()),
                ('gpt_reasoning', models.TextField()),
                ('relevance_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medley', to='pages.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.BinaryField()),
                ('model_version', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='pages.interviewsegment')),
            ],
            options={
                'indexes': [models.Index(fields=['segment'], name='pages_segme_segment_91876c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'sequence_number'], name='pages_chatm_convers_c9723a_idx'),
        ),
    ]
